# Basic Information 
title: Christian Lanius
position: PhD Student
affiliation: RWTH Aachen University
affiliation_link: https://www.ids.rwth-aachen.de
affiliation_logo: ./assets/img/ids.png
email: lanius (at) ids.rwth-aachen.de

# Search Engine Optimization (SEO)
keywords: Christian Lanius
canonical: https://lanius.org
description: Christian Lanius is a PhD at RWTH Aachen University at the chair for digital circuit design. His research interests include low power digital circuit design and compute-in-memory.

# The option is used to enable the Illinois template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?user=Qi2PSmEAAAAJ
github_link: https://github.com/christian-lanius
linkedin: https://www.linkedin.com/in/christian-lanius/
#twitter: https://twitter.com/YaoyaoLiu1/

# Images 
#avatar: https://img.yliu.me/avatar_new.jpg

# Footnotes
#footnote: Feel free to use my website's source code.
#footnote_link: https://github.com/yaoyao-liu/minimal-light



# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
